remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
title: The Artificial Guide to a Great Human Life
description: A practical guide to self-direction in the age of AI
show_downloads: false
